// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace UItestCloudExample.iOS
{
	public partial class TestTableViewController : UIViewController
	{
		public TestTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
