// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace UItestCloudExample.iOS
{
	public partial class TestLoginViewController : UIViewController
	{
		public TestLoginViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {

            btnLogin.TouchUpInside += delegate {
                if (txfPass.Text == "123")
                {
                    if (txfUser.Text=="123")
                    {
                        TestHomeViewController vc = new TestHomeViewController();
                        this.PresentViewController(vc,true,null);

                    }
                }
                    
            };

            base.ViewDidLoad();
        }
	}
}
